---
# file:  ~/env/ansible/roles/awscli/tasks/main.yml
#
# Install AWS CLI v2 (https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html)

- name: install prequesite packages
  become: yes
  apt:
    update_cache: yes
    state: latest
    name:
      - unzip

- name: download aws-cli (v2) installer
  unarchive:
    mode: '0755'
    remote_src: yes
    creates: /tmp/aws
    src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp"

- name: run the installer
  become: true
  command:
    cmd: "/tmp/aws/install"
    creates: "/usr/local/bin/aws"
  register: aws_install

- name: show installer output
  debug:
    var: aws_install
    verbosity: 2

- name: create awscli config dir for user
  file:
    path: "{{ ansible_env.HOME }}/.aws"
    state: directory
    mode: "0700"

- name: install awscli config for user
  template:
    src: config.ini
    dest: "{{ ansible_env.HOME }}/.aws/config"
    mode: "0600"

- name: touch awscli credentials file for user
  file:
    path: "{{ ansible_env.HOME }}/.aws/credentials"
    state: touch
    mode: "0600"

...
