##  ~/.bash_logout:  executed by bash(1) when login shell exits.  ####
#
# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
    [ -x `which clear` ] && clear
fi

## Local Variables:
## mode: shell-script
## sh-shell: bash
## End:
