---
# file:  ~/env/ansible/tools.yml
#
# roles to install various tools I use.
#

- hosts: all
  tasks:

  - name: install pass package
    # https://www.passwordstore.org/
    become: yes
    tags: pass
    apt:
      state: latest
      name:
        - pass
        - sshpass

- hosts: all
  vars:
    etcd_ver:   "v3.4.14"
    golang_ver: "1.17"
    protoc_ver: "3.14.0"
  roles:
    - { role: ansible,     tags: ansible }
    - { role: docker,      tags: docker }
    - { role: dockercli,   tags: dockercli }
    - { role: etcdctl,     tags: etcdctl }
    - { role: vicecli,     tags: vicecli }
    - { role: grip,        tags: grip }        ## GitHub Previewer

    # Language tools (for dev)
    - { role: python,      tags: python }    ## TODO
    - { role: golang,      tags: golang }

    # Cloudy tools
    - { role: gcloud_sdk,  tags: gcloud }
    - { role: awscli,      tags: awscli }
    - { role: terraform,   tags: terraform }
    - { role: alohomora,   tags: alohomora }

...
