---
# file:  ~/env/ansible/tools.yml
#
# roles to install various tools I use.
#

- hosts: all
  tasks:

  - name: install packages
    become: yes
    apt:
      state: latest
      name:
        - build-essential
        - pass
        - python3-venv
        - python3-pip
        - sshpass

  - name: install ansible
    become: yes
    pip:
      name: ansible

- hosts: all
  vars:
    golang_ver: "1.15.3"
  roles:
    - { role: docker,      tags: docker }
    - { role: vicecli,     tags: vicecli }

    # Language tools (for dev)
    # - { role: python,      tags: python }    ## TODO
    - { role: golang,      tags: golang }

    # Cloudy tools
    - { role: gcloud_sdk,  tags: gcloud }
    - { role: awscli,      tags: awscli }
    - { role: terraform,   tags: terraform }
    - { role: alohomora,   tags: alohomora }

...
