---
# file: ~/env/ansible/vjump.yml  ## work jump box

- hosts: all
  tasks:

  - name: install packages
    become: yes
    apt:
      state: latest
      name:
        - build-essential
        - pass
        - python3-venv
        - python3-pip
        - sshpass

  - name: install ansible
    become: yes
    pip:
      name: ansible

- hosts: all
  roles:
    - { role: docker }
    - { role: gcloud_sdk }
    - { role: awscli }
    - { role: terraform }
    - { role: golang, golang_ver: "1.15.3" }

...
