---
# file:  ~/env/ansible/roles/alohomora/tasks/main.yml
#
# Install Viasat's alohomora - AWS SAML
# - https://github.com/Viasat/alohomora
# - https://pypi.org/project/alohomora/

- name: install prequesite packages
  become: yes
  apt:
    update_cache: yes
    state: latest
    name:
      - python3-pip

- name: install alohomora
  become: yes
  pip:
    name: alohomora

- name: install alohomora config for user
  template:
    src: alohomora.ini
    dest: "{{ ansible_env.HOME }}/.alohomora"
    mode: "0600"

...
